apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecom-1
  region: us-west-2   # EKS supported region

managedNodeGroups:
  - name: managed-ng-public
    desiredCapacity: 2
    spot: true
    instancesDistribution:
      instanceTypes: ["m5.large", "c5.large", "c3.large"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: capacity-optimized
