apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-cart
  namespace: ecom
  labels: 
    component: cart
    project: ecom
    tier: app
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "ecom-catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-cart
  namespace: ecom
  labels: 
    component: cart
    project: ecom
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cart
      project: ecom
      tier: app
  template:
    metadata:
      labels:
        component: cart
        project: ecom
        tier: app
    spec:
      containers:
        - name: ecom-cart
          image: mohan9866007322/cart:v1
          # BEST PRACTICE: Explicitly declare the port the container listens on
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecom-cart
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-cart
  namespace: ecom
  labels:
    component: cart
    project: ecom
    tier: app
spec:
  selector:
    component: cart
    project: ecom
    tier: app
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080