apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-shipping
  namespace: ecom
  labels: 
    component: shipping
    project: ecom
    tier: app
data:
  # WARNING: Verify these keys against your application's source code!
  # If it connects to the database:
  DB_HOST: "mysql"
  # If it connects to the cart service we created earlier:
  CART_ENDPOINT: "ecom-cart:8080" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-shipping
  namespace: ecom
  labels: 
    component: shipping
    project: ecom
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shipping
      project: ecom
      tier: app
  template:
    metadata:            
      labels:
        component: shipping
        project: ecom
        tier: app
    spec:               
      containers:             
        - name: ecom-shipping
          image: mohan9866007322/shipping:v1
          # BEST PRACTICE: Explicitly declare the port
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ecom-shipping
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-shipping
  namespace: ecom
  labels:
    component: shipping
    project: ecom
    tier: app
spec:
  selector:
    component: shipping
    project: ecom
    tier: app
  ports:
  - protocol: TCP
    port: 8080 
    targetPort: 8080