apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: ecom
  labels:
    component: rabbitmq
    project: ecom
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: "cmFiYml0bXF1" # base64 encoded value of 'rabbitmquser'
  RABBITMQ_DEFAULT_PASS: "cmFiYml0bXFwcGFzcw==" # base64 encoded value of 'rabbitmqpass'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-rabbitmq
  namespace: ecom
  labels: 
    component: rabbitmq
    project: ecom
    tier: database 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: ecom
      tier: database 
  template:
    metadata:            
      labels:
        component: rabbitmq
        project: ecom
        tier: database 
    spec:               
      containers:             
        - name: rabbitmq
          image: rabbitmq:3
          envFrom:
            - secretRef:
                name: rabbitmq-secret

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: ecom
  labels:
    component: rabbitmq
    project: ecom
    tier: database
spec:
  selector:
    component: rabbitmq
    project: ecom
    tier: database
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672 
