apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-mongodb
  namespace: ecom
  labels: 
    component: mongodb
    project: ecom
    tire: Database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
      project: ecom
      tire: Database
  template:
    metadata:            
      labels:
        component: mongodb
        project: ecom
        tire: Database
    spec:               
      containers:             
        - name: mongodb
          image: mohan9866007322/mongodb:v1